pipeline {
    agent any

    stages {
        stage('Checkout Codebase') {
            steps {
                cleanWs()
                checkout scm: [$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/victoriamvg/Calculadora.git']]]
            }
        }
        stage('Build') {
            steps {
                bat 'cd lib/ && curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.0/junit-platform-console-standalone-1.7.0-all.jar'
                bat 'cd src &&  javac -cp "../lib/junit-platform-console-standalone-1.7.0-all.jar" AppTest.java App.java'
            }
        }
        stage('Test') {
            steps{
                bat 'cd src/ && java -jar ../lib/junit-platform-console-standalone-1.7.0-all.jar -cp "." --select-class AppTest --reports-dir="reports"'
            }
        }
        stage('Deploy') {
            steps {
                bat 'cd src/ && java App'
            }
        }
    }
}